export const dynamic = 'force-dynamic'

import { NextRequest, NextResponse } from 'next/server'
import { getUserId } from '@/lib/get-user-id'

export async function POST(req: NextRequest) {
  const userId = await getUserId()
  if (!userId) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

  const { title, markdown } = await req.json()
  if (!markdown) return NextResponse.json({ error: 'No content' }, { status: 400 })

  // Convert markdown to styled HTML document
  const html = `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>${title || 'Document'}</title>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.css">
<style>
  @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap');
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { font-family: 'Inter', -apple-system, sans-serif; color: #1a1a2e; line-height: 1.7; padding: 40px 60px; max-width: 800px; margin: 0 auto; }
  h1 { font-size: 24px; font-weight: 700; margin: 32px 0 12px; color: #0f0f23; border-bottom: 2px solid #e5e5e5; padding-bottom: 8px; }
  h2 { font-size: 20px; font-weight: 600; margin: 28px 0 10px; color: #1a1a2e; border-bottom: 1px solid #eee; padding-bottom: 6px; }
  h3 { font-size: 16px; font-weight: 600; margin: 20px 0 8px; color: #2d2d44; }
  p { margin-bottom: 12px; font-size: 14px; }
  ul, ol { margin: 8px 0 12px 24px; }
  li { margin-bottom: 4px; font-size: 14px; }
  blockquote { border-left: 3px solid #6366f1; padding-left: 16px; margin: 16px 0; color: #555; font-style: italic; }
  code { background: #f4f4f8; padding: 2px 6px; border-radius: 4px; font-size: 13px; font-family: 'SF Mono', monospace; }
  pre { background: #1a1a2e; color: #e5e5e5; padding: 16px 20px; border-radius: 8px; overflow-x: auto; margin: 16px 0; }
  pre code { background: none; padding: 0; color: inherit; font-size: 13px; }
  table { width: 100%; border-collapse: collapse; margin: 16px 0; font-size: 13px; }
  th { background: #f4f4f8; padding: 8px 12px; text-align: left; font-weight: 600; border: 1px solid #e5e5e5; }
  td { padding: 8px 12px; border: 1px solid #e5e5e5; }
  hr { border: none; border-top: 1px solid #e5e5e5; margin: 24px 0; }
  .katex-display { margin: 20px 0; text-align: center; }
  .header-meta { color: #888; font-size: 12px; margin-bottom: 24px; }
  strong { font-weight: 600; }
  @media print {
    body { padding: 20px 40px; }
    pre { white-space: pre-wrap; word-wrap: break-word; }
  }
</style>
</head>
<body>
<div class="header-meta">Generated by Release EDU · ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</div>
${markdownToHtml(markdown)}
<script src="https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.js"><\/script>
<script>
document.querySelectorAll('.math-inline').forEach(el => {
  katex.render(el.textContent, el, { throwOnError: false, displayMode: false });
});
document.querySelectorAll('.math-display').forEach(el => {
  katex.render(el.textContent, el, { throwOnError: false, displayMode: true });
});
<\/script>
</body>
</html>`

  return new Response(html, {
    headers: {
      'Content-Type': 'text/html; charset=utf-8',
      'Content-Disposition': `inline; filename="${(title || 'document').replace(/[^a-zA-Z0-9 ]/g, '')}.html"`,
    },
  })
}

// Simple markdown to HTML converter
function markdownToHtml(md: string): string {
  let html = md
    // Escape HTML entities first
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')

  // Block math ($$...$$)
  html = html.replace(/\$\$([\s\S]*?)\$\$/g, '<div class="math-display katex-display">$1</div>')
  // Inline math ($...$)
  html = html.replace(/\$([^\$\n]+?)\$/g, '<span class="math-inline">$1</span>')

  // Code blocks
  html = html.replace(/```(\w*)\n([\s\S]*?)```/g, (_, lang, code) => {
    return `<pre><code class="language-${lang}">${code.trim()}</code></pre>`
  })

  // Headers
  html = html.replace(/^### (.+)$/gm, '<h3>$1</h3>')
  html = html.replace(/^## (.+)$/gm, '<h2>$1</h2>')
  html = html.replace(/^# (.+)$/gm, '<h1>$1</h1>')

  // Bold and italic
  html = html.replace(/\*\*\*(.+?)\*\*\*/g, '<strong><em>$1</em></strong>')
  html = html.replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
  html = html.replace(/\*(.+?)\*/g, '<em>$1</em>')

  // Inline code
  html = html.replace(/`([^`]+)`/g, '<code>$1</code>')

  // Blockquotes
  html = html.replace(/^&gt; (.+)$/gm, '<blockquote><p>$1</p></blockquote>')

  // Horizontal rules
  html = html.replace(/^---$/gm, '<hr>')

  // Tables
  html = html.replace(/^\|(.+)\|\n\|[-| ]+\|\n((?:\|.+\|\n?)+)/gm, (_, header, body) => {
    const ths = header.split('|').map((h: string) => `<th>${h.trim()}</th>`).join('')
    const rows = body.trim().split('\n').map((row: string) => {
      const tds = row.replace(/^\||\|$/g, '').split('|').map((d: string) => `<td>${d.trim()}</td>`).join('')
      return `<tr>${tds}</tr>`
    }).join('')
    return `<table><thead><tr>${ths}</tr></thead><tbody>${rows}</tbody></table>`
  })

  // Unordered lists
  html = html.replace(/^- (.+)$/gm, '<li>$1</li>')
  html = html.replace(/(<li>[\s\S]*?<\/li>\n?)+/g, '<ul>$&</ul>')

  // Ordered lists
  html = html.replace(/^\d+\. (.+)$/gm, '<li>$1</li>')

  // Paragraphs — wrap remaining lines
  html = html.replace(/^(?!<[hupotdbl]|<\/|<hr|<li|<div|<span|<blockquote|<pre|<table)(.+)$/gm, '<p>$1</p>')

  // Clean up double newlines
  html = html.replace(/\n{2,}/g, '\n')

  return html
}
