import { NextRequest, NextResponse } from 'next/server'
import { cookies } from 'next/headers'
import { getServerSession } from 'next-auth'
import { authOptions } from '@/lib/auth'
import { dbStore } from '@/lib/db-store'
import { getUserId } from '@/lib/get-user-id'
import { researchTopic, researchExistingCurricula } from '@/lib/gemini'
import { normalizeCurriculumTracks } from '@/lib/title-normalize'
import { getUserLanguage, curriculumLanguageDirective, type Language } from '@/lib/get-user-language'
import prisma from '@/lib/prisma'
// Types no longer needed — IDs are generated by Prisma, not from Claude's response

// Without an explicit maxDuration, Vercel kills this function at the plan
// default — far below the ~60–150s a real curriculum generation needs. Every
// kill or failure dropped users onto the generic fallback template.
export const maxDuration = 300

interface OnboardingProfile {
  interests: string[]
  strengths: string[]
  weaknesses: string[]
  learningStyle: string
  personalityTraits: string[]
  aspirations: string
  /** beginner | intermediate | advanced | professional — desired depth/rigor. */
  advancementLevel?: string
  educationFrustrations?: string[]
  baselineAssessment: {
    math: number
    writing: number
    science: number
    history: number
    criticalThinking: number
  }
}

export async function POST(req: NextRequest) {
  const cookieStore = await cookies()
  const isDemo = cookieStore.get('demo-mode')?.value === 'true'
  const session = await getServerSession(authOptions)

  if (!session?.user && !isDemo) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  }
  if (isDemo) {
    return NextResponse.json({ success: true, demo: true })
  }

  const body = await req.json() as { profile?: OnboardingProfile; conversationHistory?: string; manual?: boolean }
  let { profile } = body
  const isManualRegeneration = body.manual === true

  // Manual regenerations (from the "Regenerate with AI" button) are capped at
  // 2 per curriculum lifetime. The counter resets when the user does Start
  // Over. System-initiated calls (onboarding's first run, dashboard layout's
  // auto-recovery) do NOT count against this limit — only user-initiated
  // button clicks do.
  // Default cap is 2, but the per-student limit is admin-adjustable
  // (StudentProfile.manualRegenerationLimit, set from the admin panel).
  const DEFAULT_MANUAL_REGENERATIONS = 2
  let manualRegenerationLimit = DEFAULT_MANUAL_REGENERATIONS
  if (isManualRegeneration) {
    const userIdForCheck = await getUserId()
    const sp = await prisma.studentProfile.findUnique({
      where: { userId: userIdForCheck },
      select: { manualRegenerationCount: true, manualRegenerationLimit: true },
    })
    const used = sp?.manualRegenerationCount ?? 0
    manualRegenerationLimit = sp?.manualRegenerationLimit ?? DEFAULT_MANUAL_REGENERATIONS
    if (used >= manualRegenerationLimit) {
      const limitLang = await getUserLanguage(userIdForCheck)
      return NextResponse.json({
        error: limitLang === 'zh'
          ? `本课程的 ${manualRegenerationLimit} 次重新生成机会已用完。点击"重新开始"可重置，或请你的导师增加次数。`
          : `You've used all ${manualRegenerationLimit} regenerations for this curriculum. Click Start Over to reset, or ask your Mentor for more.`,
        manualRegenerationCount: used,
        manualRegenerationLimit,
      }, { status: 429 })
    }
  }

  // If no structured profile but conversation history provided, extract profile via Claude
  if (!profile && body.conversationHistory) {
    const extractKey = process.env.ANTHROPIC_API_KEY
    if (extractKey) {
      try {
        const Anthropic = (await import('@anthropic-ai/sdk')).default
        const client = new Anthropic({ apiKey: extractKey })
        const result = await client.messages.create({
          model: 'claude-opus-4-8',
          max_tokens: 1500,
          messages: [{
            role: 'user',
            content: `Extract a detailed student profile from this onboarding conversation. Be thorough — extract EVERY topic, sub-topic, keyword, and domain the student mentioned or implied interest in.

Conversation:
${body.conversationHistory}

CRITICAL INSTRUCTIONS for the "interests" field:
- Do NOT just list the surface-level topic (e.g. "prediction markets"). Break it into 4-8 specific sub-disciplines and related fields the student would need to master.
- Example: if someone says "I want to build a quant model for Polymarket" → interests should be ["quantitative modeling", "prediction markets", "probabilistic reasoning", "stochastic processes", "market microstructure", "Bayesian inference", "data-driven decision making", "risk analysis"]
- Think: what university courses, textbook chapters, and research areas does this interest actually span?

For "aspirations": be specific about what they want to BUILD, not just learn.

For "advancementLevel": the depth/rigor the student asked for — one of exactly "beginner", "intermediate", "advanced", or "professional". Use what they explicitly said; if they did not specify, infer conservatively from their age/background/goals and default to "intermediate".

Return ONLY valid JSON, no markdown fences:
{"interests":["specific-sub-discipline-1","specific-sub-discipline-2","...at least 4-8"],"strengths":["..."],"weaknesses":["..."],"learningStyle":"visual / hands-on / reading / discussion","personalityTraits":["..."],"aspirations":"specific thing they want to build or achieve","advancementLevel":"beginner | intermediate | advanced | professional","educationFrustrations":["..."],"baselineAssessment":{"math":5,"writing":5,"science":5,"history":5,"criticalThinking":5}}`
          }]
        })
        {
          const { recordAnthropicUsage } = await import('@/lib/usage')
          recordAnthropicUsage(result.usage, { model: 'claude-opus-4-8', feature: 'curriculum' })
        }
        const text = ((result.content[0] as { type: string; text?: string }).text || '').trim().replace(/^```(?:json)?\n?/, '').replace(/\n?```$/, '')
        profile = JSON.parse(text) as OnboardingProfile
      } catch (err) {
        console.error('[CurriculumGenerate] Profile extraction failed, falling back to generic profile:', err)
        // Don't return 500 — onboarding should still complete with a default curriculum.
        // The user can refine their profile later via the dashboard.
      }
    }
  }

  const apiKey = process.env.ANTHROPIC_API_KEY

  const storeUserId = await getUserId()
  const store = dbStore.forUser(storeUserId)

  // The student's language drives BOTH the Claude prompt directive and every
  // fallback template below. A zh student must never see English mixed into
  // their curriculum, even when AI generation fails (CLAUDE.md hard rule).
  const lang: Language = await getUserLanguage(storeUserId)

  // Recovery fallback: if neither profile nor conversationHistory was given,
  // try to rebuild a profile from the chat-saved StudentProfile fields. This
  // is the path used when the user got stuck with isOnboarded=true but no
  // curriculum (a previous gen failed before saving tracks).
  if (!profile) {
    try {
      const sp = await store.getProfile()
      if (sp && (sp.interests || sp.aspirations)) {
        const parseList = (v: string | null | undefined): string[] => {
          if (!v) return []
          try { const p = JSON.parse(v); return Array.isArray(p) ? p : [v] } catch { return [v] }
        }
        profile = {
          interests: parseList(sp.interests),
          strengths: parseList(sp.strengths),
          weaknesses: parseList(sp.weaknesses),
          learningStyle: sp.learningStyle || 'visual',
          personalityTraits: [],
          aspirations: sp.aspirations || '',
          educationFrustrations: [],
          baselineAssessment: { math: 5, writing: 5, science: 5, history: 5, criticalThinking: 5 },
        }
        console.log(`[CurriculumGenerate] Recovery: rebuilt profile from DB for ${storeUserId}`)
      }
    } catch (err) {
      console.error('[CurriculumGenerate] Recovery profile load failed:', err)
    }
  }

  // Last-resort fallback: build a minimal profile so the user is never stuck.
  if (!profile) {
    profile = {
      interests: ['general learning'],
      strengths: [],
      weaknesses: [],
      learningStyle: 'visual',
      personalityTraits: [],
      aspirations: '',
      educationFrustrations: [],
      baselineAssessment: { math: 5, writing: 5, science: 5, history: 5, criticalThinking: 5 },
    }
  }

  // Load setup metadata — age (from birthdate), occupation, education,
  // name, organization. All of these get folded into the curriculum prompt
  // so Claude calibrates depth/vocabulary/examples to who the student is.
  let learnerAge: number | null = null
  let learnerOccupation: string | null = null
  let learnerEducation: string | null = null
  let learnerName: string | null = null
  let learnerOrgLine: string | null = null
  try {
    const savedProfile = await store.getProfile()
    const rawMeta = savedProfile?.roadmapState
      ? (JSON.parse(savedProfile.roadmapState)?._profileMeta ?? {})
      : {}
    if (rawMeta.birthdate) {
      const birth = new Date(rawMeta.birthdate)
      const today = new Date()
      learnerAge = today.getFullYear() - birth.getFullYear()
      if (today < new Date(today.getFullYear(), birth.getMonth(), birth.getDate())) learnerAge--
    }
    learnerOccupation = rawMeta.occupation ?? null
    learnerEducation = rawMeta.education ?? null
    learnerName = rawMeta.name ?? null
    learnerOrgLine = rawMeta.isIndividual
      ? 'learning independently (no formal school/org)'
      : (rawMeta.organization ? `at ${rawMeta.organization}` : null)
    // Carry a previously-saved level forward (e.g. on Regenerate, where the
    // profile is rebuilt from the DB and won't carry advancementLevel).
    if (!profile.advancementLevel && rawMeta.advancementLevel) {
      profile.advancementLevel = rawMeta.advancementLevel
    }
  } catch { /* ignore */ }

  // Normalize + default the level once so every downstream use is consistent.
  {
    const lvl = (profile.advancementLevel || '').toLowerCase()
    profile.advancementLevel = ['beginner', 'intermediate', 'advanced', 'professional'].includes(lvl) ? lvl : 'intermediate'
  }

  // Save profile and mark onboarded. Persist the chosen level into _profileMeta
  // so regenerations and Bob's teaching keep it.
  try {
    const sp = await store.getProfile()
    let rs: Record<string, unknown> = {}
    try { rs = sp?.roadmapState ? JSON.parse(sp.roadmapState as string) : {} } catch { rs = {} }
    rs._profileMeta = { ...((rs._profileMeta as Record<string, unknown>) ?? {}), advancementLevel: profile.advancementLevel }
    await store.updateProfile({
      interests: JSON.stringify(profile.interests || []),
      strengths: JSON.stringify(profile.strengths || []),
      weaknesses: JSON.stringify(profile.weaknesses || []),
      learningStyle: profile.learningStyle || 'visual',
      aspirations: profile.aspirations || '',
      roadmapState: JSON.stringify(rs),
      isOnboarded: true,
    })
  } catch (err) {
    console.error('[CurriculumGenerate] Failed to save profile:', err)
  }

  // No upfront default save. If we save the generic-titled fallback first
  // and Claude later fails or times out, the user is stuck with chapters
  // like "Foundations and Vocabulary" / "Capstone Project". That was the
  // exact bug surfaced in production. The dashboard's empty-state handles
  // a missing curriculum cleanly, so we only save once we have real content.

  if (!apiKey) {
    // No Claude available at all — fall back to the (now interest-specific)
    // default template so the user has SOMETHING. This branch should be rare.
    const defaultData = generateDefaultCurriculum(profile, lang)
    await saveCurriculumPlanToDb(store, defaultData).catch(err => {
      console.error('[CurriculumGenerate] Failed to save default plan:', err)
    })
    const fullPlan = await store.getCurriculumPlan()
    return NextResponse.json({ plan: fullPlan })
  }

  // 150s overall budget — Claude needs ~60-90s for 6 courses with 3-4
  // chapters each at 16k tokens. The previous 90s ceiling timed out enough
  // generations to make the fallback path visible to users; bumping to 150s
  // makes the placeholder titles rare instead of common.
  const overallStart = Date.now()
  const OVERALL_BUDGET_MS = 150_000
  const remainingBudget = () => Math.max(0, OVERALL_BUDGET_MS - (Date.now() - overallStart))

  // True only when Claude actually produced (and we saved) a real curriculum.
  // Drives the manual-regeneration counter and tells the client whether the
  // returned plan is AI-generated or a fallback/pre-existing one.
  let aiGenerated = false
  let aiError: string | null = null

  try {
    const topInterest = profile.interests[0] ?? 'technology'

    // Cap each research call at 5s — they're useful context but not worth
    // starving Claude over. If they time out, Claude still does great work
    // (stress test confirms it doesn't need this context for title quality).
    const withTimeout = <T,>(p: Promise<T>, ms: number, fallback: T): Promise<T> =>
      Promise.race([
        p,
        new Promise<T>(resolve => setTimeout(() => resolve(fallback), ms)),
      ])

    const [researchContext, curriculaResearch] = await Promise.all([
      withTimeout(researchTopic(topInterest), 5_000, ''),
      withTimeout(researchExistingCurricula(topInterest, profile.interests.slice(0, 4).join(', ')), 5_000, ''),
    ])

    const Anthropic = (await import('@anthropic-ai/sdk')).default
    const client = new Anthropic({ apiKey })

    const learnerProfileLine = [
      learnerName,
      learnerAge ? `${learnerAge} years old` : null,
      learnerOccupation,
      learnerEducation,
      learnerOrgLine,
    ].filter(Boolean).join(', ')

    // Accumulated student memory: everything Bob has learned since onboarding.
    // This is what makes a regenerated curriculum better than the first one —
    // it reflects observed strengths/struggles, not just the intake interview.
    let memoryBlock = ''
    try {
      const { getTopInsights } = await import('@/lib/insight-memory')
      const memory = await getTopInsights(storeUserId, { limit: 15 })
      if (memory.length > 0) {
        memoryBlock = `\n**Accumulated observations from tutoring sessions (weigh these heavily — they're more current than the onboarding profile):**\n${memory.map(i => `- [${i.type}] ${i.content}`).join('\n')}\n`
      }
    } catch { /* non-critical — generate without memory */ }

    let prompt = `You are an educational curriculum designer. Create a personalized curriculum plan for a student with this profile:

${learnerProfileLine ? `**Learner Profile:** ${learnerProfileLine} — CRITICAL: calibrate ALL curriculum complexity, depth, vocabulary, pacing, and example choices to this profile. A 10-year-old needs simple, concrete, playful content. A 25-year-old working professional needs career-relevant, rigorous, efficient content. A graduate student needs research-grade depth.\n` : ''}**Interests:** ${profile.interests.join(', ')}
**Strengths:** ${profile.strengths.join(', ')}
**Weaknesses:** ${profile.weaknesses.join(', ')}
**Learning Style:** ${profile.learningStyle}
**Personality:** ${profile.personalityTraits.join(', ')}
**Aspirations:** ${profile.aspirations}
${profile.educationFrustrations?.length ? `**What they disliked about traditional education (AVOID these in curriculum design):** ${profile.educationFrustrations.join(', ')}` : ''}
**Baseline Assessment:** Math: ${profile.baselineAssessment.math}/10, Writing: ${profile.baselineAssessment.writing}/10, Science: ${profile.baselineAssessment.science}/10, History: ${profile.baselineAssessment.history}/10, Critical Thinking: ${profile.baselineAssessment.criticalThinking}/10
**Target Academic Level:** ${profile.advancementLevel || 'intermediate'}

## TARGET ACADEMIC LEVEL — CALIBRATE EVERY CHAPTER TO THIS (the student explicitly chose it)
The student asked for a **${profile.advancementLevel || 'intermediate'}**-level course. This is the single strongest signal for how hard, how deep, and how professional the chapters should be. Map it to a real university tier and pitch EVERY chapter — topic selection, depth, vocabulary, prerequisites, and the difficulty of the project — to that tier:
- **beginner** → first-exposure / 100-level intro survey courses (and for young learners, accessible and concrete). Assume no prior background; build intuition first, minimal jargon, lots of examples. Chapters cover the foundational vocabulary and core ideas only.
- **intermediate** → 200–300-level undergraduate courses. Assume the basics are known; go into mechanisms, methods, and real applications with standard field terminology. Chapters mirror a typical sophomore/junior syllabus.
- **advanced** → 400-level / senior undergraduate-to-early-graduate courses. Rigorous treatment: proofs/derivations where relevant, primary-source reading, edge cases, current debates. Chapters mirror an honors/capstone or first-year-grad syllabus.
- **professional** → graduate-seminar / industry-practitioner depth. Cutting-edge, specialized, and directly applicable to professional practice or research. Chapters assume strong fundamentals and go straight to the hard, valuable material — the depth a working expert or PhD student would expect.

Anchor your chapter choices to how REAL universities sequence this subject at the chosen tier (use the existing-curricula research above). Do NOT water an advanced learner down, and do NOT overwhelm a beginner — match the tier exactly. The chosen level OVERRIDES a generic reading of age/occupation when they conflict (a motivated 15-year-old who asked for "advanced" gets advanced; a professional who asked for a "beginner" refresher gets beginner).
${memoryBlock}

**Research on their top interest (${topInterest}):**
${researchContext.slice(0, 800)}

**Existing curricula from real institutions (reference these for structure, topic ordering, and depth):**
${curriculaResearch.slice(0, 1200)}
${body.conversationHistory ? `\n**Raw onboarding conversation (use this to understand the student deeply — extract every keyword, sub-interest, and implied domain):**\n${body.conversationHistory.slice(0, 1500)}` : ''}

---

## CURRICULUM DESIGN PRINCIPLES — APPLY ALL OF THESE

**TERMINOLOGY (use consistently — both internally in this JSON and externally to the student):**
- A **track** is one of the two top-level groupings ("Foundations" or "Interest-Based").
- A **course** is an item inside a track. (Formal academic course title.)
- A **chapter** is an item inside a course. (One focused concept, 5–12 hours.)
- Never use the words "subject" or "module" to refer to courses — always say "course". The output JSON's track names contain courses; each course's "modules" array contains chapters.

**1. TIME BUDGET — ~2 MONTHS TOTAL**
The entire curriculum (all courses + projects) should be completable in approximately 2 months of dedicated study (~150–200 total hours). Budget time accordingly:
- Interest-based courses: ~120–150 hours total across 3–5 courses (each course 25–40 hours)
- Foundation courses: ~30–50 hours total across 2–3 courses (each course 10–20 hours)
- Each chapter within a course: 5–12 hours
- Allocate time realistically — a chapter on "Measure Theory" needs more hours than "What is a Prediction Market?"

**2. BREADTH AND SPECIFICITY**
- Interest-based courses must cover the FULL landscape of the student's domain — not just one narrow slice. If someone wants quant finance, they need probability theory AND market microstructure AND risk modeling AND data analysis — not 5 variations of the same topic.
- Each course must be specific enough to have a clear identity — broad enough to contain 3–5 meaningful chapters.
- Foundation courses must each be a distinct discipline — no overlap between them, and no overlap with interest courses.

**3. LOGICAL FLOW AND COHERENCE**
- Courses should be ordered so prerequisites come first. Within each course, chapters must build on each other sequentially.
- The student should never encounter a chapter that requires knowledge from a chapter they haven't reached yet.
- Cross-course dependencies: if "Stochastic Calculus" requires "Probability Theory" (a foundation course), the foundation course should be positioned to be studied first or in parallel.
- Each chapter's description must make clear what it builds on and what it enables.

**4. RELEVANCE TO USER INTERESTS AND NEEDS**
- Every course must have a clear line connecting it to the student's stated aspirations and interests from the onboarding conversation.
- No filler courses. If a course doesn't directly serve the student's goals, it shouldn't exist.
- Chapter topics should reflect what the student would actually encounter in pursuing their aspiration — drawn from real curricula, textbooks, and professional practice in that field.

**5. INTEREST VS FOUNDATION STRUCTURE**
- **Interest-based track** = courses that are deep dives INTO the student's passion. These ARE the thing they want to learn. Specialized sub-disciplines. ~75–80% of total time.
- **Foundation track** = courses in traditional academic disciplines that SUPPORT the passion but aren't the passion itself. Adjacent disciplines that make the student more capable. ~20–25% of total time.
- The two tracks should feel complementary — a student studying both should see how foundation courses enhance their understanding of the interest courses.

**6. PERSONAL CONTEXT — AGE, PROFESSION, BACKGROUND**
- The student's age, occupation, education level, and geographic/cultural background must shape EVERY decision: topic selection, difficulty, examples, vocabulary, pacing.
- A 15-year-old high school student gets accessible foundations and discovery-oriented chapters. A 30-year-old finance professional gets rigorous, career-applicable, efficient content that respects what they already know.
- If the student's profession is relevant to their interest (e.g. a software engineer studying game dev), skip basics they already know and start at their actual level.
- Geographic/cultural context matters for examples and references — use relevant institutions, industries, and real-world contexts from their region where possible.

**7. REFERENCE REAL CURRICULA**
- Use the existing curricula research provided above as a structural reference. Your course breakdown, chapter ordering, and topic coverage should be informed by how real universities, MOOCs, and professional programs teach these subject areas.
- You don't need to copy them — but the sequence and depth should be defensible against a real syllabus. If MIT teaches stochastic calculus by starting with probability spaces before Itô's lemma, your chapters should reflect a similar logical ordering.
- Where your curriculum diverges from standard programs (because of the student's unique goals), that's fine — but the divergence should be intentional, not accidental.

---

Create courses inside TWO distinct tracks — this structure is MANDATORY in every curriculum:

---

**1. INTEREST-BASED TRACK (type: "project") — EXACTLY 3 courses, ~75–80% of total hours**

**HARD REQUIREMENT: Generate exactly 3 distinct interest-based courses — not 2, not 4. A curriculum with any other count is invalid and will be rejected.**

These courses go DEEP into the student's specific interest area. They are specialized, field-specific, and directly about what the student loves.

**NAMING RULE — NON-NEGOTIABLE:**
- Use formal academic course titles like you'd see in a university course catalog
- Examples: "Stochastic Calculus", "Market Microstructure", "Bayesian Probability & Inference", "Buddhist Epistemology", "Game Engine Architecture"
- NEVER append "Path", "Track", "Journey", "Module", or "Basics" to the name
- NEVER use vague names like "Intro to [topic]", "Build Something Real", "[Topic] Fundamentals"
- Each name must be a precise sub-discipline, not a generic umbrella term

**DO NOT ECHO THE STUDENT'S INTERESTS AS COURSE NAMES — THIS IS THE #1 FAILURE MODE.**
The student's stated interests (e.g. "cryptosecurity", "investing", "company due diligence") are DOMAINS, not courses. Each domain must be DECOMPOSED into 3 specific sub-disciplines. A course named after the domain itself is invalid and will be rejected.
- Student says "cryptosecurity" → INVALID course names: "Cryptosecurity", "Cryptosecurity I", "Advanced Cryptosecurity". VALID: "Symmetric Cryptography & Block Ciphers", "Public-Key Infrastructure & RSA", "Network Security Protocols (TLS, IPsec, Tor)"
- Student says "investing" → INVALID: "Investing", "Investing II". VALID: "Equity Valuation & DCF Modeling", "Behavioral Finance & Market Psychology", "Portfolio Theory & Risk Management"
- Student says "company due diligence" → INVALID: "Company Due Diligence". VALID: "Financial Statement Analysis", "Operational & Legal Diligence", "Industry & Competitive Landscape Analysis"
- Student says "game development" → INVALID: "Game Development". VALID: "Game Engine Architecture", "Procedural Level Design", "Multiplayer Networking & Replication"
- Student says "marine biology" → INVALID: "Marine Biology". VALID: "Coral Reef Ecology", "Marine Vertebrate Behavior", "Ocean Chemistry & pH Dynamics"

The test: read your course name aloud. If it's the same word a casual person would use to describe the entire domain ("she's into cryptosecurity"), it's wrong. Course names should sound like the second-week-of-class title, not the first-day-introduce-yourself title.

**COURSE DESCRIPTION QUALITY — three rules: SPECIFIC, COMPREHENSIVE, SIMPLE.**
Each course's description (1-2 sentences) must:
- **SPECIFIC**: name the actual concepts/methods covered, not vague claims. ✗ "Master the foundations of cryptography." ✓ "Covers symmetric ciphers (AES, ChaCha20), block-cipher modes, and key management — with hands-on implementation in Python."
- **COMPREHENSIVE**: a student reading just the description should know what they'll be able to do at the end. List 2-3 concrete capabilities or topics.
- **SIMPLE**: plain language calibrated to the student's age. No marketing fluff ("unlock", "master", "transform", "journey", "dive deep"). State what the course is.
- FORBIDDEN OPENERS: "Master…", "Unlock…", "Dive into…", "Explore the world of…", "Embark on…", "Journey through…". Just describe the content.

**TITLE CASE — MANDATORY for both course names AND chapter titles:**
- Capitalize every meaningful word: "Game Engine Architecture", NOT "Game engine architecture"
- Small grammatical words ("of", "and", "in", "the", "for", "to") stay lowercase mid-phrase: "Philosophy of Mind", "Theory and Practice"
- The first and last word are always capitalized regardless
- This applies to EVERY title in the JSON — course names, chapter titles, projectIdea text. Lowercase mid-sentence words anywhere will fail review.

**CHAPTERS ARE LEARNING CONTENT ONLY — NEVER PROJECTS.**

This is the most important rule. Chapters teach concepts, theory, principles, and technique. They are NOT "build something" units. The app has a SEPARATE projects section — every interest course already has its own "projectIdea" field (one capstone per course) where building/creating/shipping work belongs. Chapters are the textbook; the project section is the lab.

- A chapter title that names a project, build, ship, hands-on activity, or capstone is INVALID and will be rejected.
- "Capstone Project", "First Hands-On Project", "Build Your First X", "End-to-End System Project", "Final Project", "Project Workshop", "Hackathon Sprint", "Practicum" — all FORBIDDEN as chapter titles. They belong in the "projectIdea" field, not in "modules".
- Even when a chapter teaches a skill that's used in projects, the chapter title must name the CONCEPT being taught, not the act of building. "Procedural Level Design" ✓ (a concept) — "Build a Procedural Level" ✗ (an activity).

**CHAPTER TITLE QUALITY — three non-negotiable rules: SPECIFIC, COMPREHENSIVE, SIMPLE.**
- **SPECIFIC** — name the actual concept, not a phase, stage, or progress label. Every title must contain at least one concrete technical noun drawn from the course's discipline. "Bayes' Theorem in Practice" ✓ — "Advanced Topics" ✗. "Modular Arithmetic and Caesar Ciphers" ✓ — "Core Principles" ✗. "RSA Encryption" ✓ — "Foundations and Vocabulary" ✗.
- **COMPREHENSIVE** — the title alone must describe the core of what the chapter teaches. A student reading the title with no other context should know what they'll learn. If the title could plausibly belong to any course, it's wrong.
- **SIMPLE** — plain, audience-calibrated language. A 12-year-old's chapter title is not jargon-stacked; a graduate student's chapter title is precise but not pretentious. One concept per title — don't string three together.
- Read like a real textbook's table of contents.
- FORBIDDEN PATTERNS (these will be rejected): progress labels — "Foundations and Vocabulary", "Core Principles", "Advanced Topics", "Tools and Techniques", "Real-World Applications", "Professional Practice"; project-shaped titles — "Capstone Project", "Hands-On Project", "End-to-End System Project", "First [X] Project", "Build a [X]", "Building a [X] System", "Ship Your First [X]"; templated titles — "Intro to [course]", "[course] Fundamentals", "Tools & Techniques for [course]".
- Do NOT echo the course name in chapter titles ("Introduction to Game Programming" inside the "Game Programming" course is redundant).
- Examples of good chapter titles: "Random Variables and Distributions", "Bid-Ask Spreads and Order Flow", "The Anchoring Effect", "Brownian Motion and Random Walks", "RSA Encryption", "Maillard Reaction and Flavor Compound Formation", "Modular Arithmetic: Clock Math and Its Cryptographic Powers".

Examples by interest:
- Prediction markets → "Stochastic Calculus", "Market Microstructure", "Bayesian Probability & Prediction Markets", "Expected Value Theory", "Psychology of Risk & Decision-Making"
- Buddhist philosophy → "Tibetan Buddhist Studies", "Buddhist Epistemology & Logic", "Philosophy of Mind in Buddhism", "Comparative Buddhist Schools"
- Game development → "Game Engine Architecture", "Procedural Level Design", "Narrative Systems & Storytelling", "Multiplayer Networking"
- Marine biology → "Coral Reef Ecology", "Marine Vertebrate Behavior", "Ocean Chemistry & pH Dynamics"

The student should recognize these courses as directly about their passion — not adjacent to it.

---

**2. FOUNDATION TRACK (type: "core") — EXACTLY 3 courses**

**HARD REQUIREMENT: Generate exactly 3 distinct foundation courses — not 2, not 4. A curriculum with any other count is invalid and will be rejected.**

These are specific traditional academic courses — not the interest itself but disciplines that support it. Each must have a precise, formal course name (e.g. "Linear Algebra", "Probability Theory", "Behavioral Economics") — NEVER just "Foundations", "Math", or "Science". Name them as a university registrar would.

Draw from the full taxonomy of academic disciplines:
- **Natural Sciences**: Physics, Chemistry, Biology, Earth Sciences, Astronomy
- **Formal Sciences**: Mathematics, Statistics, Logic, Computer Science
- **Social Sciences**: Psychology, Sociology, Economics, Political Science, Anthropology, Geography
- **Humanities**: History, Philosophy, Linguistics, Literature, Ethics
- **Applied Sciences**: Engineering principles, Environmental Science, Medicine basics
- **Arts & Culture**: Art History, Music Theory, Film Studies, Architecture

The key rule: foundation courses should be **sparsely relevant** to the interest — adjacent enough to add value, but not directly about it. They should feel like broadening general education, not an extension of the interest itself.

Examples:
- Buddhist philosophy student → Mathematics & Logic, Psychology of Consciousness, World History & Civilizations
- Game developer → Linear Algebra, Cognitive Psychology, Economics (game economies)
- Marine biologist → Chemistry, Statistics & Data Analysis, Environmental Policy
- Music producer → Physics (acoustics), Mathematics, Music History

NOT directly related (good), but adds genuine value to a well-rounded thinker in that field.

---

Additional rules:
- Foundation courses complement but do NOT duplicate the interest-based track's courses
- Each course is a distinct discipline with its own chapter progression
- Keep it focused and clean — no bloat or generic padding
- Each track MUST have a "type" field: "project" for interest-based, "core" for foundation

---

**CHAPTER DESIGN — THINK BEFORE WRITING:**

Before generating chapters for each course, reason through:
1. What is this student's current level in this domain? (Use their baseline assessment and conversation history)
2. What learning goals does this course serve for their aspirations?
3. What sequence of chapters would build understanding from their current level to competence?
4. How does each chapter connect to the next — what prerequisite understanding does it create?

**NAMING DISTINCTION — courses vs chapters:**

Course titles = formal course titles. Broad, formal, like a university course catalog.
- Good: "Stochastic Calculus", "Market Microstructure", "Probability Theory", "Behavioral Economics"
- These are the names a student would see in a course listing.

Chapter titles = lesson-level topics. Narrow, concrete, completable in 1–2 sessions.
- Good: "Random Variables & Distributions", "Bid-Ask Spreads & Order Flow", "Bayes' Theorem in Practice", "The Anchoring Effect"
- These are what you'd see in a textbook table of contents — one focused concept per chapter.
- NOT mini-courses ("Introduction to Probability"), NOT vague ("Key Concepts"), NOT projects ("Capstone Project", "Build Your First Model", "Hands-On Practicum"). Projects belong in the course's "projectIdea" field, never as chapters.

**Chapter requirements:**
- Each course needs 3–4 chapters
- Each chapter covers ONE focused CONCEPT — something a student could learn in 1–2 study sessions (5–12 hours). Chapters are about understanding, not building. The capstone project is a separate field, not a chapter.
- The difficulty progression should be calibrated to the student's baseline — a math-strong student doesn't need "What is a Variable?", a math-weak student shouldn't start with measure theory
- Every chapter must have a clear "why" — how does mastering this chapter move the student toward their aspirations?

For each chapter: title, description (1-2 sentences explaining what the student will learn and why it matters for their goals), type ("project" or "core-content"), subject (the parent course name), estimatedHours, skills (2-3 specific skills gained), aiRationale (1 sentence connecting this chapter to the student's learning goals), status (first chapter of first track "in-progress", rest "not-started")

Return ONLY valid JSON (no markdown). Do NOT include any "id" fields — IDs will be generated by the database.
{
  "profileSummary": "1-2 sentences",
  "primaryStrengths": ["..."],
  "primaryInterests": ["..."],
  "learningStyle": "...",
  "personalityTraits": ["..."],
  "tracks": [
    {
      "name": "[Formal Academic Title e.g. Stochastic Calculus, Buddhist Epistemology]", "description": "...", "color": "#3B82F6", "type": "project",
      "projectIdea": "[SHORT capstone artifact name, 3-8 words, e.g. 'Annotated Kernel Subsystem Audit' — names the thing the student builds. NO 'Build:' prefix, NO explanation inside the title]",
      "projectDescription": "[COMPREHENSIVE 2-4 sentence brief: exactly what the student will build, the scope and any options, what accompanies it (write-up, benchmark, demo), and the central technical/intellectual challenge]",
      "modules": [
        {"title": "[Specific topic e.g. Brownian Motion & Random Walks]", "description": "Learn X because it enables Y for your goal of Z", "type": "project", "subject": "...", "estimatedHours": 12, "skills": ["...", "..."], "aiRationale": "...", "status": "in-progress"},
        {"title": "[Next specific topic]", "description": "...", "type": "project", "subject": "...", "estimatedHours": 10, "skills": ["...", "..."], "aiRationale": "...", "status": "not-started"}
      ]
    },
    {
      "name": "[Specific Traditional Course e.g. Linear Algebra, Probability Theory, Behavioral Economics]", "description": "...", "color": "#10B981", "type": "core",
      "modules": [
        {"title": "[Specific topic within the course]", "description": "...", "type": "core-content", "subject": "...", "estimatedHours": 8, "skills": ["...", "..."], "aiRationale": "...", "status": "not-started"}
      ]
    }
  ]
}

IMPORTANT: Every entry in "tracks" represents a COURSE (terminology note: the JSON field is named "tracks" for backward compat, but each entry is a course inside one of the two tracks — Foundations or Interest-Based — distinguished by its "type" field). Every entry MUST have a "type" field — either "project" or "core". Every "project" entry MUST include BOTH a "projectIdea" field (a SHORT artifact title, 3-8 words — names what the student builds, NOT just the course name) AND a "projectDescription" field (the comprehensive brief — every detail lives in the description, never in the title). Generate EXACTLY 3 interest-based courses AND EXACTLY 3 foundation courses — 6 courses total. Any other count is invalid. Each course must have 3–4 chapters with specific topic titles. Each course's "modules" array contains the full chapter objects (NOT string IDs). Do NOT include any "id" fields anywhere.`

    // Language: generate course/chapter text in the student's chosen language
    // while keeping JSON keys + enum values English so the parser works.
    prompt += curriculumLanguageDirective(lang)

    // Start directly at 16000 tokens. We previously tried 12000 first and only
    // retried at 16000 if Claude hit the cap — but that retry doubled total
    // latency and frequently exhausted the budget, triggering the generic
    // fallback. Going straight to 16000 costs ~5% more tokens but cuts the
    // p99 latency in half and dramatically reduces fallback firings.
    const claudeBudget = Math.max(20_000, remainingBudget() - 5_000)

    // Auto-retry on Anthropic `overloaded_error` (HTTP 529). Transient capacity
    // blip, resolves in seconds — without retry we'd fall through to the
    // generic-default fallback for an issue that isn't actually a code failure.
    const isOverload = (err: unknown): boolean => {
      if (!err || typeof err !== 'object') return false
      const e = err as { status?: number; error?: { error?: { type?: string }; type?: string } }
      if (e.status === 529) return true
      const innerType = e.error?.error?.type ?? e.error?.type
      return innerType === 'overloaded_error'
    }
    const sleep = (ms: number) => new Promise<void>(r => setTimeout(r, ms))
    const RETRY_DELAYS_MS = [1500, 3000, 6000]

    const callClaude = async (maxTokens: number) => {
      let lastErr: unknown = null
      for (let attempt = 0; attempt < 4; attempt++) {
        try {
          return await client.messages.create({
            model: 'claude-sonnet-4-6',
            max_tokens: maxTokens,
            messages: [{ role: 'user', content: prompt }],
          }, { signal: AbortSignal.timeout(claudeBudget) })
        } catch (err) {
          lastErr = err
          if (isOverload(err) && remainingBudget() > 10_000 && attempt < 3) {
            const delay = RETRY_DELAYS_MS[attempt] ?? 6000
            console.warn(`[CurriculumGenerate] Anthropic overloaded — retrying in ${delay}ms (attempt ${attempt + 2}/4)`)
            await sleep(delay)
            continue
          }
          throw err
        }
      }
      throw lastErr
    }

    let result = await callClaude(16000)
    // If Claude hit the cap even at 16000 (very rare), retry once at 20000.
    if (result.stop_reason === 'max_tokens' && remainingBudget() > 20_000) {
      console.warn('[CurriculumGenerate] Hit max_tokens at 16000, retrying at 20000')
      result = await callClaude(20000)
    }

    const text = (result.content[0] as { type: string; text?: string })?.text?.trim() ?? ''
    const cleaned = text.replace(/^```(?:json)?\n?/, '').replace(/\n?```$/, '').trim()
    const generated = JSON.parse(cleaned) as {
      profileSummary: string
      primaryStrengths: string[]
      primaryInterests: string[]
      learningStyle: string
      personalityTraits: string[]
      tracks: Array<{
        name: string
        description: string
        color: string
        type: string
        projectIdea?: string
        projectDescription?: string
        modules: Array<{
          title: string
          description: string
          type: string
          subject: string
          estimatedHours: number
          skills: string[]
          aiRationale: string
          status: string
        }>
      }>
    }

    // Enforce minimum 3 subjects per track type. If Claude under-delivered
    // (which happens), pad with subjects from the default curriculum so the
    // student always sees a reasonably broad plan post-generation.
    const interestTracks = generated.tracks.filter(t => t.type === 'project')
    const foundationTracks = generated.tracks.filter(t => t.type === 'core')
    const otherTracks = generated.tracks.filter(t => t.type !== 'project' && t.type !== 'core')

    if (interestTracks.length < 3 || foundationTracks.length < 3) {
      console.warn(`[CurriculumGenerate] Claude returned ${interestTracks.length} interest + ${foundationTracks.length} foundation subjects — padding to 3+3 from defaults.`)
      const defaults = generateDefaultCurriculum(profile, lang)
      const defaultInterest = defaults.tracks.filter(t => t.type === 'project')
      const defaultFoundation = defaults.tracks.filter(t => t.type === 'core')
      // Pad — only add defaults whose names don't collide with what Claude generated
      const usedNames = new Set(generated.tracks.map(t => t.name.toLowerCase()))
      while (interestTracks.length < 3 && defaultInterest.length) {
        const next = defaultInterest.shift()!
        if (!usedNames.has(next.name.toLowerCase())) {
          interestTracks.push(next)
          usedNames.add(next.name.toLowerCase())
        }
      }
      while (foundationTracks.length < 3 && defaultFoundation.length) {
        const next = defaultFoundation.shift()!
        if (!usedNames.has(next.name.toLowerCase())) {
          foundationTracks.push(next)
          usedNames.add(next.name.toLowerCase())
        }
      }
    }

    const finalTracks = [...interestTracks, ...foundationTracks, ...otherTracks]

    // Save to DB — Prisma generates all IDs. The hard-guarantee block below
    // reads the plan back via store.getCurriculumPlan() so we don't need the
    // return value here.
    await saveCurriculumPlanToDb(store, {
      profileSummary: generated.profileSummary,
      primaryStrengths: generated.primaryStrengths,
      primaryInterests: generated.primaryInterests,
      learningStyle: generated.learningStyle,
      personalityTraits: generated.personalityTraits,
      tracks: finalTracks,
    })
    aiGenerated = true
  } catch (err) {
    console.error('[CurriculumGenerate] Claude generation failed — will fall through to guaranteed save:', err)
    aiError = err instanceof Error ? `${err.name}: ${err.message}`.slice(0, 200) : String(err).slice(0, 200)
  }

  // ── HARD GUARANTEE ───────────────────────────────────────────────────────
  // No code path past this point is allowed to return without a real plan
  // in the DB. Three nested fallbacks, from richest to most defensive:
  //   1. If a plan was saved during the Claude path, use it.
  //   2. Otherwise, build the interest-aware default from the user's profile.
  //   3. Otherwise, build a minimum-viable plan with a single interest track.
  // The route ALWAYS returns 200 with a non-empty `plan.tracks`. The
  // onboarding flow can trust that a successful response means a real
  // curriculum exists.
  let finalPlan = await store.getCurriculumPlan().catch(() => null)
  if (!finalPlan || finalPlan.tracks.length === 0) {
    try {
      const defaultData = generateDefaultCurriculum(profile, lang)
      await saveCurriculumPlanToDb(store, defaultData)
      finalPlan = await store.getCurriculumPlan()
    } catch (defErr) {
      console.error('[CurriculumGenerate] Interest-aware default failed — using minimum-viable plan:', defErr)
    }
  }
  if (!finalPlan || finalPlan.tracks.length === 0) {
    try {
      const zh = lang === 'zh'
      const firstInterest = (profile.interests[0] || (zh ? '通识学习' : 'General Study')).replace(/\b\w/g, c => c.toUpperCase())
      await saveCurriculumPlanToDb(store, {
        profileSummary: zh
          ? `${firstInterest} —— 初始课程。与 Bob 对话以进一步完善。`
          : `${firstInterest} — bootstrap curriculum. Talk to Bob to refine.`,
        primaryStrengths: profile.strengths,
        primaryInterests: profile.interests,
        learningStyle: profile.learningStyle,
        personalityTraits: profile.personalityTraits,
        tracks: [{
          name: firstInterest,
          description: zh ? `${firstInterest}入门。` : `Introduction to ${firstInterest}.`,
          color: '#3B82F6', type: 'project',
          modules: zh ? [
            { title: `${firstInterest}的核心概念`, description: `${firstInterest}的核心思想与基本术语。`, type: 'project', subject: firstInterest, estimatedHours: 8, skills: [firstInterest], aiRationale: '学习起点。', status: 'in-progress' },
            { title: `${firstInterest}的方法与技巧`, description: `${firstInterest}中实际使用的方法。`, type: 'project', subject: firstInterest, estimatedHours: 10, skills: [firstInterest], aiRationale: '在核心概念的基础上展开。', status: 'not-started' },
            { title: `${firstInterest}的应用实践`, description: `把${firstInterest}应用到真实问题中。`, type: 'project', subject: firstInterest, estimatedHours: 10, skills: [firstInterest], aiRationale: '综合前面章节所学。', status: 'not-started' },
          ] : [
            { title: `${firstInterest}: Key Concepts`, description: `Core ideas and vocabulary in ${firstInterest}.`, type: 'project', subject: firstInterest, estimatedHours: 8, skills: [firstInterest], aiRationale: 'Starting point.', status: 'in-progress' },
            { title: `${firstInterest}: Methods and Techniques`, description: `Practical methods used in ${firstInterest}.`, type: 'project', subject: firstInterest, estimatedHours: 10, skills: [firstInterest], aiRationale: 'Builds on key concepts.', status: 'not-started' },
            { title: `${firstInterest}: Applied Practice`, description: `Applying ${firstInterest} to real problems.`, type: 'project', subject: firstInterest, estimatedHours: 10, skills: [firstInterest], aiRationale: 'Synthesizes earlier chapters.', status: 'not-started' },
          ],
        }],
      })
      finalPlan = await store.getCurriculumPlan()
    } catch (mvpErr) {
      console.error('[CurriculumGenerate] CRITICAL: minimum-viable plan save failed:', mvpErr)
    }
  }

  // Increment the manual-regeneration counter only if this call was driven
  // by a user clicking "Regenerate with AI" AND Claude actually produced a
  // new plan. Failed generations (which leave the old/fallback plan in
  // place) don't count against the user's budget.
  let manualRegenerationCount = 0
  if (finalPlan && finalPlan.tracks.length > 0) {
    if (isManualRegeneration && aiGenerated) {
      const updated = await prisma.studentProfile.update({
        where: { userId: storeUserId },
        data: { manualRegenerationCount: { increment: 1 } },
        select: { manualRegenerationCount: true, manualRegenerationLimit: true },
      }).catch(() => null)
      manualRegenerationCount = updated?.manualRegenerationCount ?? 0
      manualRegenerationLimit = updated?.manualRegenerationLimit ?? manualRegenerationLimit
    } else {
      const current = await prisma.studentProfile.findUnique({
        where: { userId: storeUserId },
        select: { manualRegenerationCount: true, manualRegenerationLimit: true },
      }).catch(() => null)
      manualRegenerationCount = current?.manualRegenerationCount ?? 0
      manualRegenerationLimit = current?.manualRegenerationLimit ?? manualRegenerationLimit
    }
  }

  return NextResponse.json({
    plan: finalPlan,
    manualRegenerationCount,
    manualRegenerationLimit,
    aiGenerated,
    aiError,
  })
}

/** Save the curriculum data into the DB via dbStore — all IDs are generated by Prisma */
async function saveCurriculumPlanToDb(
  store: ReturnType<typeof dbStore.forUser>,
  data: {
    profileSummary: string
    primaryStrengths: string[]
    primaryInterests: string[]
    learningStyle: string
    personalityTraits: string[]
    tracks: Array<{
      name: string
      description: string
      color: string
      type: string
      projectIdea?: string
      projectDescription?: string
      modules: Array<{
        title: string
        description: string
        type: string
        subject: string
        estimatedHours: number
        skills: string[]
        aiRationale: string
        status: string
      }>
    }>
  }
) {
  // Systematic title normalization: every track name, chapter title, and
  // chapter subject runs through the shared normalizer regardless of source
  // (default template, Claude output, future generators). This is the one
  // place to enforce Title Case and remove subject-name echoing in chapters.
  const normalizedTracks = normalizeCurriculumTracks(data.tracks)

  // No IDs passed — Prisma auto-generates them for tracks and modules
  return await store.setCurriculumPlan({
    profileSummary: data.profileSummary,
    primaryStrengths: data.primaryStrengths,
    primaryInterests: data.primaryInterests,
    learningStyle: data.learningStyle,
    personalityTraits: data.personalityTraits,
    version: 1,
    tracks: normalizedTracks.map((t, idx) => ({
      name: t.name,
      description: t.description,
      color: t.color,
      type: t.type,
      projectIdea: t.projectIdea,
      projectDescription: t.projectDescription,
      order: idx,
      modules: (t.modules ?? []).map((m, mIdx) => ({
        title: m.title,
        description: m.description,
        type: m.type,
        subject: m.subject,
        status: m.status,
        progress: 0,
        estimatedHours: m.estimatedHours,
        prerequisites: [],
        skills: m.skills,
        aiRationale: m.aiRationale,
        order: mIdx,
      })),
    })),
  })
}

function generateDefaultCurriculum(profile: OnboardingProfile, lang: Language = 'en') {
  const zh = lang === 'zh'
  // Proper Title Case so subject names like "Game Programming Fundamentals"
  // capitalize every meaningful word — not just the first letter. Small
  // grammatical words ("of", "and", "in", etc.) stay lowercase mid-phrase.
  const SMALL_WORDS = new Set(['a', 'an', 'the', 'and', 'but', 'or', 'nor', 'as', 'at', 'by', 'for', 'in', 'of', 'on', 'to', 'up', 'vs', 'via', '&'])
  const titleCase = (s: string) =>
    s.toLowerCase().split(/\s+/).map((w, i) => {
      if (i > 0 && SMALL_WORDS.has(w)) return w
      return w.charAt(0).toUpperCase() + w.slice(1)
    }).join(' ').trim()

  // Strip introductory-sounding suffixes that we'll add back via course
  // numbering — e.g. "Game Programming Fundamentals" → "Game Programming"
  // so we can produce three textbook-style courses without "Fundamentals
  // Foundations"–style redundancy.
  const stripIntroSuffix = (s: string) =>
    s.replace(/\s+(fundamentals|foundations|basics|introduction|intro|essentials|101)$/i, '').trim() || s

  const interests = profile.interests.filter(Boolean)
  const rawI1 = interests[0] ?? 'general study'
  const i1Full = titleCase(rawI1)              // "Game Programming Fundamentals"
  const i1Stem = titleCase(stripIntroSuffix(rawI1)) // "Game Programming"

  // For the 2nd and 3rd subjects, prefer real interests from the conversation;
  // otherwise fall back to a numbered-course sequence on the top interest.
  const i2 = interests[1] ? titleCase(interests[1]) : (zh ? `${i1Stem}进阶：方法与实践` : `${i1Stem} II: Methods and Practice`)
  const i3 = interests[2] ? titleCase(interests[2]) : (zh ? `高级${i1Stem}` : `Advanced ${i1Stem}`)

  // Fallback chapter titles. The hard rule from FOUNDATION.md is that titles
  // must be SPECIFIC, COMPREHENSIVE, SIMPLE — they should name a concrete
  // concept, not a phase label. Without Claude we can't pick domain-specific
  // concepts perfectly, so we use phrasings that AT LEAST embed the subject
  // stem in a way the title normalizer won't strip (the normalizer removes
  // the subject name when it appears verbatim, so we use phrases like
  // "Building Blocks of X" instead of "X: Building Blocks").
  //
  // NOTE: This fallback path should be rare — the route's primary Claude call
  // now uses 150s budget + 16k max_tokens, so true failures are uncommon.
  // When fallbacks do fire, the UI's "Regenerate with AI" banner prompts
  // the user to re-trigger a real Claude run.
  // Chinese chapter titles use "X的…" phrasing — the title normalizer's
  // subject-stripping relies on \b word boundaries, which never match CJK
  // text, so these titles survive normalization intact.
  const buildChapters = (subjectFull: string, subjectStem: string, firstStatus: string): Array<{ title: string; description: string; type: string; subject: string; status: string; estimatedHours: number; skills: string[]; aiRationale: string }> => zh ? [
    { title: `${subjectStem}的基本概念`, description: `深入学习${subjectStem}之前需要掌握的基础概念、术语和思维模型。`, type: 'project', subject: subjectFull, status: firstStatus, estimatedHours: 8, skills: [`${subjectStem}术语`, '概念框架'], aiRationale: `${subjectStem}的扎实入门起点。` },
    { title: `${subjectStem}的核心方法`, description: `${subjectStem}领域从业者实际使用的核心技巧、框架与分析工具。`, type: 'project', subject: subjectFull, status: 'not-started', estimatedHours: 10, skills: [`${subjectStem}方法`, '方法选择'], aiRationale: `这些是${subjectStem}的实用工具。` },
    { title: `${subjectStem}的应用问题`, description: `${subjectStem}研究与实践中的真实问题，以及该领域的工具如何应对它们。`, type: 'project', subject: subjectFull, status: 'not-started', estimatedHours: 10, skills: ['应用推理', '批判性评估'], aiRationale: `把${subjectStem}与现实问题和前沿研究联系起来。` },
  ] : [
    { title: `Building Blocks of ${subjectStem}`, description: `The foundational concepts, vocabulary, and mental models you need before deeper work in ${subjectStem}.`, type: 'project', subject: subjectFull, status: firstStatus, estimatedHours: 8, skills: [`${subjectStem} vocabulary`, 'Conceptual framing'], aiRationale: `A grounded entry point into ${subjectStem}.` },
    { title: `Working Methods in ${subjectStem}`, description: `The core techniques, frameworks, and analytical tools practitioners actually use in ${subjectStem}.`, type: 'project', subject: subjectFull, status: 'not-started', estimatedHours: 10, skills: [`${subjectStem} techniques`, 'Method selection'], aiRationale: `These are the working tools of ${subjectStem}.` },
    { title: `Applied Problems in ${subjectStem}`, description: `Real-world problems from research and practice in ${subjectStem}, and how the field's tools address them.`, type: 'project', subject: subjectFull, status: 'not-started', estimatedHours: 10, skills: ['Applied reasoning', 'Critical evaluation'], aiRationale: `Connecting ${subjectStem} to live problems and current research.` },
  ]

  // Interest-based courses. The PROJECT goes in projectIdea (one per course),
  // never as a chapter. Chapter titles name concepts, not activities.
  const courseDescription = (stem: string) => zh
    ? `${stem}的概念、方法与当代应用。`
    : `Concepts, methods, and contemporary applications in ${stem}.`
  const capstoneTitle = (stem: string) => zh
    ? `${stem}原创作品`
    : `An Original ${stem} Artifact`
  const capstoneBrief = (stem: string) => zh
    ? `综合本课程三章所学，完成一份原创${stem}作品。具体形式（论文、演示或汇报）和范围由学生自定，经导师审核确定。`
    : `An original ${stem} artifact that synthesizes the three chapters — student-defined scope and concrete form (paper, demo, presentation), mentor-approved.`

  const interestTracks = [
    {
      name: i1Full,
      description: courseDescription(i1Stem),
      color: '#3B82F6',
      type: 'project',
      projectIdea: capstoneTitle(i1Stem),
      projectDescription: capstoneBrief(i1Stem),
      modules: buildChapters(i1Full, i1Stem, 'in-progress'),
    },
    {
      name: i2,
      description: courseDescription(i2),
      color: '#8B5CF6',
      type: 'project',
      projectIdea: capstoneTitle(i2),
      projectDescription: capstoneBrief(i2),
      modules: buildChapters(i2, i2, 'not-started'),
    },
    {
      name: i3,
      description: courseDescription(i3),
      color: '#EC4899',
      type: 'project',
      projectIdea: capstoneTitle(i3),
      projectDescription: capstoneBrief(i3),
      modules: buildChapters(i3, i3, 'not-started'),
    },
  ]

  // Three foundation subjects — broadly relevant to any interest, framed
  // through the top interest so the connection feels intentional.
  const foundationTracks = zh ? [
    {
      name: '数学基础',
      description: `应用于${i1Stem}的数学与逻辑思维。`,
      color: '#10B981',
      type: 'core',
      modules: [
        { title: '逻辑与量化推理', description: `逻辑、模式与量化推理 —— 通过${i1Stem}中的例子来学习。`, type: 'core-content', subject: '数学基础', status: 'not-started', estimatedHours: 8, skills: ['逻辑', '模式识别'], aiRationale: `数学是${i1Stem}的底层支撑，用你真正关心的例子来教。` },
        { title: '概率与统计', description: '在不确定性中推理 —— 分布、抽样与推断。', type: 'core-content', subject: '数学基础', status: 'not-started', estimatedHours: 8, skills: ['概率', '统计思维'], aiRationale: '现实世界的大多数问题都是概率性的。' },
        { title: '问题解决策略', description: '如何拆解难题、识别结构并找到解法。', type: 'core-content', subject: '数学基础', status: 'not-started', estimatedHours: 6, skills: ['问题拆解', '启发式方法'], aiRationale: '通用的问题解决能力比任何具体工具都更持久。' },
      ],
    },
    {
      name: '沟通与写作',
      description: '向不同受众清晰表达复杂想法。',
      color: '#F59E0B',
      type: 'core',
      modules: [
        { title: '技术写作', description: '写出尊重读者时间的文档、简报和说明。', type: 'core-content', subject: '沟通与写作', status: 'not-started', estimatedHours: 6, skills: ['技术写作', '编辑润色'], aiRationale: '最优秀的从业者也能讲清楚自己的工作。' },
        { title: '论证与说服', description: '用证据构建并捍卫观点 —— 写提案和评审时必不可少。', type: 'core-content', subject: '沟通与写作', status: 'not-started', estimatedHours: 6, skills: ['论证', '基于证据的写作'], aiRationale: '说服他人是把工作落地的另一半。' },
        { title: '展示你的成果', description: '向导师、同伴和评审清晰地讲解你的项目。', type: 'core-content', subject: '沟通与写作', status: 'not-started', estimatedHours: 5, skills: ['公开表达', '演示'], aiRationale: '成果的影响力取决于你分享它的能力。' },
      ],
    },
    {
      name: '研究与批判性思维',
      description: '评估信息来源、检验假设、严谨思考。',
      color: '#06B6D4',
      type: 'core',
      modules: [
        { title: '信息来源评估', description: '分辨证据的强弱 —— 论文、博客与炒作。', type: 'core-content', subject: '研究与批判性思维', status: 'not-started', estimatedHours: 5, skills: ['来源评估', '审慎怀疑'], aiRationale: '在任何领域，知道该相信什么都是一种超能力。' },
        { title: '研读一手文献', description: `阅读并剖析${i1Stem}领域的一手论文与参考资料。`, type: 'core-content', subject: '研究与批判性思维', status: 'not-started', estimatedHours: 7, skills: ['主动阅读', '笔记方法'], aiRationale: '直接读原始资料胜过依赖二手总结。' },
        { title: '提出更好的问题', description: '从模糊的好奇心走向聚焦、可回答的探究。', type: 'core-content', subject: '研究与批判性思维', status: 'not-started', estimatedHours: 5, skills: ['问题界定', '假设设计'], aiRationale: '更好的问题带来更好的答案，任何领域都如此。' },
      ],
    },
  ] : [
    {
      name: 'Mathematical Foundations',
      description: `Mathematical and logical thinking applied to ${i1Stem}.`,
      color: '#10B981',
      type: 'core',
      modules: [
        { title: 'Logic and Quantitative Reasoning', description: `Logic, patterns, and quantitative reasoning — framed through ${i1Stem}.`, type: 'core-content', subject: 'Mathematical Foundations', status: 'not-started', estimatedHours: 8, skills: ['Logic', 'Pattern recognition'], aiRationale: `Math underpins ${i1Stem}. Taught through examples you actually care about.` },
        { title: 'Probability and Statistics', description: 'Reasoning under uncertainty — distributions, sampling, and inference.', type: 'core-content', subject: 'Mathematical Foundations', status: 'not-started', estimatedHours: 8, skills: ['Probability', 'Statistical thinking'], aiRationale: `Most real-world questions are probabilistic.` },
        { title: 'Problem-Solving Strategies', description: 'How to break down hard problems, recognize structure, and find solutions.', type: 'core-content', subject: 'Mathematical Foundations', status: 'not-started', estimatedHours: 6, skills: ['Decomposition', 'Heuristics'], aiRationale: `Generalizable problem-solving outlasts any specific tool.` },
      ],
    },
    {
      name: 'Communication and Writing',
      description: 'Expressing complex ideas clearly to different audiences.',
      color: '#F59E0B',
      type: 'core',
      modules: [
        { title: 'Technical Writing', description: 'Produce documentation, briefs, and explanations that respect the reader\'s time.', type: 'core-content', subject: 'Communication and Writing', status: 'not-started', estimatedHours: 6, skills: ['Technical writing', 'Editing'], aiRationale: `The best practitioners can also explain their work.` },
        { title: 'Argument and Persuasion', description: 'Build and defend positions with evidence — essential for proposals and reviews.', type: 'core-content', subject: 'Communication and Writing', status: 'not-started', estimatedHours: 6, skills: ['Argumentation', 'Evidence-based writing'], aiRationale: `Convincing others is half of getting work shipped.` },
        { title: 'Presenting Your Work', description: 'Speaking clearly about your projects to mentors, peers, and reviewers.', type: 'core-content', subject: 'Communication and Writing', status: 'not-started', estimatedHours: 5, skills: ['Public speaking', 'Demos'], aiRationale: `Your work is only as impactful as your ability to share it.` },
      ],
    },
    {
      name: 'Research and Critical Thinking',
      description: 'Evaluating sources, testing assumptions, and thinking rigorously.',
      color: '#06B6D4',
      type: 'core',
      modules: [
        { title: 'Source Evaluation', description: 'Distinguish strong evidence from weak — papers, blogs, hype.', type: 'core-content', subject: 'Research and Critical Thinking', status: 'not-started', estimatedHours: 5, skills: ['Source evaluation', 'Skepticism'], aiRationale: `In any field, knowing what to trust is a superpower.` },
        { title: 'Reading Primary Sources', description: `Read and dissect primary papers and references in ${i1Stem}.`, type: 'core-content', subject: 'Research and Critical Thinking', status: 'not-started', estimatedHours: 7, skills: ['Active reading', 'Note-taking'], aiRationale: `Going to the source beats relying on summaries.` },
        { title: 'Asking Better Questions', description: 'Move from vague curiosity to focused, answerable inquiry.', type: 'core-content', subject: 'Research and Critical Thinking', status: 'not-started', estimatedHours: 5, skills: ['Question framing', 'Hypothesis design'], aiRationale: `Better questions produce better answers, in any domain.` },
      ],
    },
  ]

  return {
    profileSummary: zh
      ? `对${i1Stem}充满热情。${profile.aspirations ? `目标：${profile.aspirations}。` : ''}本课程围绕${i1Full}、${i2}和${i3}开展真实项目，同时夯实最重要的基础能力。`
      : `Passionate about ${i1Stem}. ${profile.aspirations ? `Aspires to ${profile.aspirations}.` : ''} This curriculum focuses on building real projects in ${i1Full}, ${i2}, and ${i3} while strengthening the foundations that matter most.`,
    primaryStrengths: profile.strengths.slice(0, 3),
    primaryInterests: profile.interests.slice(0, 3),
    learningStyle: profile.learningStyle || (zh ? '动手实践' : 'Hands-on'),
    personalityTraits: profile.personalityTraits.slice(0, 3),
    tracks: [...interestTracks, ...foundationTracks],
  }
}
